name: Archive 9000

on:
  workflow_dispatch:

jobs:
  archive-9000:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Directory
        run: mkdir -p "${GITHUB_WORKSPACE}/repositories"

      - name: Check URL File
        run: |
          if [ ! -f "${GITHUB_WORKSPACE}/repositories/url.txt" ]; then
            echo "repositories/url.txt not found!"
            exit 1
          fi

      - name: Download
        run: |
          set -e
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          while IFS= read -r u; do
            [ -z "$u" ] && continue
            f="$repo_dir/$(basename "$u")"
            curl -fSLs "$u" -o "$f" || wget -q "$u" -O "$f"
          done < "$repo_dir/url.txt"

      - name: Archive
        run: |
          set -e
          shopt -s nullglob
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          date_str=$(date +'%Y.%m.%d')
          archive="${GITHUB_WORKSPACE}/repositories.$date_str.tar.xz"
          xz_files=("$repo_dir"/*.xz)
          if [ ${#xz_files[@]} -gt 0 ]; then
            tar -cJf "$archive" -C "$repo_dir" $(basename -a "${xz_files[@]}")
            rm "${xz_files[@]}"
          else
            echo "no .xz files to archive."
          fi

      - name: Commit & push archive and changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add -A
          git commit -m "$(date +%Y-%m-%d) Update (archive and all changes)" || exit 0
          git push origin HEAD
