name: Archive 9000

on:
  workflow_dispatch:

jobs:
  archive-9000:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Download Files (url.txt)
        run: |
          mkdir -p repositories

          REPO_DIR="${GITHUB_WORKSPACE}/repositories"
          URL_LIST="${REPO_DIR}/url.txt"
          if [ ! -f "$URL_LIST" ]; then
            echo "No url.txt found at $URL_LIST"
            exit 1
          fi

          while read -r url; do
            [ -z "$url" ] && continue
            filename=$(basename "$url")
            if ! curl -fsSL "$url" -o "${REPO_DIR}/$filename"; then
              wget -q "$url" -O "${REPO_DIR}/$filename" || echo "Failed to download $url."
            fi
          done < "$URL_LIST"

      - name: Compress, Commit, Push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          REPO_DIR="${GITHUB_WORKSPACE}/repositories"
          cd "$REPO_DIR"
          shopt -s nullglob
          for file in *; do
            [ -f "$file" ] && xz -9 -e -k "$file" && rm "$file"
          done

          if ls *.xz 1> /dev/null 2>&1; then
            tar -cJf "${GITHUB_WORKSPACE}/repositories.tar.xz" *.xz && rm *.xz
          fi

          cd "${GITHUB_WORKSPACE}"
          DATE_STR=$(date +"%Y-%m-%d")
          ARCHIVE_NAME="repositories.${DATE_STR}.tar.xz"
          mv -f repositories.tar.xz "$ARCHIVE_NAME"
          git add repositories/ "$ARCHIVE_NAME"
          git commit -m "${DATE_STR} Update" || exit 0
          git push origin HEAD:main
