name: Archive 9000

on:
  workflow_dispatch:

jobs:
  archive-9000:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p "${GITHUB_WORKSPACE}/repositories"

      - run: '[ -f "${GITHUB_WORKSPACE}/repositories/url.txt" ]'

      - run: |
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          while IFS= read -r u; do
            [ -z "$u" ] && continue
            f="$repo_dir/$(basename "$u")"
            curl -fSLs "$u" -o "$f" || wget -q "$u" -O "$f" || true
          done < "$repo_dir/url.txt"

      - run: |
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          cd "$repo_dir"
          for f in *; do
            [ -f "$f" ] && [ "$f" != url.txt ] && [ "$f" != repositories.tar.xz ] && xz -9ek "$f" && rm "$f"
          done
          ls *.xz 2>/dev/null && tar -cJf repositories.tar.xz *.xz && rm *.xz || :

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          cd "$repo_dir"
          today=$(date +%Y-%m-%d)
          [ -f repositories.tar.xz ] && [ ! -f repositories.$today.tar.xz ] && mv repositories.tar.xz repositories.$today.tar.xz || :
          git add -A
          git commit -m "$today Update (archive and all changes)" || :
          git push origin HEAD
