name: Archive 9000

on:
  workflow_dispatch:

jobs:
  archive-9000:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Directory
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/repositories"
          mkdir -p "${GITHUB_WORKSPACE}/backup/repositories"

      - name: Check URL File
        run: |
          if [ ! -f "${GITHUB_WORKSPACE}/repositories/url.txt" ]; then
            echo "repositories/url.txt not found!"
            exit 1
          fi

      - name: Download
        run: |
          set -e
          repo_dir="${GITHUB_WORKSPACE}/repositories"
          while IFS= read -r u; do
            [ -z "$u" ] && continue
            f="$repo_dir/$(basename "$u")"
            curl -fSLs "$u" -o "$f" || wget -q "$u" -O "$f"
          done < "$repo_dir/url.txt"

      - name: Archive
        run: |
          d="${GITHUB_WORKSPACE}/repositories"
          dd="${GITHUB_WORKSPACE}/backup/repositories"
          dt=$(date +%Y.%m.%d)
          mkdir -p "$d"
          shopt -s nullglob
          for f in "$d"/*; do [ -f "$f" ] && xz -9 "$f"; done
          [ -n "$(ls -A "$d"/*.xz 2>/dev/null)" ] && tar -cJvf "$d/repositories.tar.xz" -C "$d" --remove-files *.xz
          mv -f "$d/repositories.tar.xz" "$d/$dt.tar.xz"
          mv -f "$d/$dt.tar.xz" "$dd/$dt.tar.xz"

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add -A
          git commit -m "$(date +%Y-%m-%d) Update (archive and all changes)" || exit 0
          git push origin HEAD
