name: Archive 9000

on:
  workflow_dispatch:
    inputs:
      commit-message:
        description: 'Update.'
        required: false
        default: 'Update.'

jobs:
  download_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@latest

      - name: Check Download Directory
        run: mkdir -p downloads

      - name: Download Files (url.txt)
        run: |
          while read -r url; do
            [ -z "$url" ] && continue
            filename=$(basename "$url")
            curl -fsSL "$url" -o "downloads/$filename"
          done < url.txt

      - name: Configure Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add downloads/
          git commit -m "${{ github.event.inputs.commit-message }}" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
